### ISSUE TITLE
Consider releasing 2.5?

### ISSUE THREAD

**Issue by rahij** [super-csv/super-csv#125] opened 2017-02-23 15:44 UTC
Hey folks, I'm trying to pick up this commit: https://github.com/super-csv/super-csv/pull/103, but it seems like there hasn't been a release after that change. Do you have a timeline on when the next release could be? Thanks!

**Comment by ash211** [comment] 2017-02-23 20:20
Duplicate of #115

**Comment by kbilsted** [comment] 2017-02-23 22:22
@ZioberMichal  Any progress with the releases? :-)

**Closed** 2017-02-23 22:22 UTC
Labels: duplicate
