### ISSUE TITLE
Custom escape character

### ISSUE THREAD

**Issue by ZioberMichal** [super-csv/super-csv#79] opened 2015-11-01 22:38 UTC
User should be able to set custom escape character. Currently "quote character" and "escape character" are the same. 

Due to [RFC 4180](https://tools.ietf.org/html/rfc4180) paragraph 2.7:
> If double-quotes are used to enclose fields, then a double-quote
> appearing inside a field must be escaped by preceding it with
> another double quote.  For example:
>
> "aaa","b""bb","ccc"

If user change escape character to "[" below should be valid:
```
"aaa","b["bb","ccc"
```

Update "testCustomEscape" test in [ReadingFeaturesTest](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/ReadingFeaturesTest.java) and [WritingFeaturesTest](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/WritingFeaturesTest.java) classes.

**Comment by ash211** [comment] 2016-05-23 23:53
Should close this as a dupe of #14

**Closed** 2016-05-24 06:15 UTC
Labels: duplicate, enhancement, task
